# Generated by Django 2.2 on 2021-03-12 14:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stock', models.IntegerField()),
                ('expiration_date', models.DateField(default=product.models.get_deadline, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
